
-- Sample SQL Queries for Production Line Database
-- Generated by ETL Pipeline Testing Script

-- Query 1: Total records loaded
SELECT COUNT(*) FROM sensor_readings;

-- Query 2: View hourly summary for a specific line
SELECT * FROM hourly_summary
WHERE line_id = 'Line_1'
ORDER BY hour DESC
LIMIT 10;

-- Query 3: Find high defect rate hours
SELECT hour, line_id, machine_id, defect_rate
FROM hourly_summary
WHERE defect_rate > 5.0
ORDER BY defect_rate DESC;

-- Query 4: Check data quality distribution
SELECT data_quality, COUNT(*) as count
FROM sensor_readings
GROUP BY data_quality;

-- Query 5: Join sensor data with quality checks
SELECT
    s.timestamp,
    s.machine_id,
    s.temperature,
    q.result as quality_result
FROM sensor_readings s
LEFT JOIN quality_checks q
    ON s.machine_id = q.machine_id
    AND s.timestamp = q.timestamp
LIMIT 10;

-- Query 6: Average temperature by machine
SELECT
    machine_id,
    AVG(temperature) as avg_temp,
    MIN(temperature) as min_temp,
    MAX(temperature) as max_temp
FROM sensor_readings
GROUP BY machine_id;

-- Query 7: Hourly trends for a specific machine
SELECT 
    hour,
    avg_temperature,
    avg_pressure,
    avg_vibration,
    defect_rate
FROM hourly_summary
WHERE machine_id = 'machine_01'
ORDER BY hour DESC;

-- Query 8: Find anomalous readings
SELECT 
    timestamp,
    machine_id,
    temperature,
    pressure,
    vibration,
    data_quality
FROM sensor_readings
WHERE data_quality = 'invalid'
    OR temperature > 120
    OR pressure > 8
ORDER BY timestamp DESC;

-- Query 9: Quality check performance by line
SELECT 
    line_id,
    COUNT(*) as total_checks,
    SUM(CASE WHEN result = 'pass' THEN 1 ELSE 0 END) as passed,
    SUM(CASE WHEN result = 'fail' THEN 1 ELSE 0 END) as failed,
    ROUND(SUM(CASE WHEN result = 'pass' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate
FROM quality_checks
GROUP BY line_id;

-- Query 10: Peak production hours
SELECT 
    CAST(strftime('%H', hour) AS INTEGER) as hour_of_day,
    COUNT(*) as readings,
    AVG(defect_rate) as avg_defect_rate
FROM hourly_summary
GROUP BY hour_of_day
ORDER BY hour_of_day;
